In [11]:
import numpy as np

In [15]:
a = np.array([1, 2, 3])
print(type(a)) 
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [17]:
array_A = np.array([1, 2, 3, 4])

print(array_A)

[1 2 3 4]


In [22]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [3]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [3]:
import pandas as pd

movies = pd.read_csv ('https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv')

print(movies)

                                  Film    Genre            Lead Studio  \
0           Zack and Miri Make a Porno  Romance  The Weinstein Company   
1                      Youth in Revolt   Comedy  The Weinstein Company   
2   You Will Meet a Tall Dark Stranger   Comedy            Independent   
3                         When in Rome   Comedy                 Disney   
4                What Happens in Vegas   Comedy                    Fox   
..                                 ...      ...                    ...   
72                 Across the Universe  romance            Independent   
73                       A Serious Man    Drama              Universal   
74                  A Dangerous Method    Drama            Independent   
75                          27 Dresses   Comedy                    Fox   
76                (500) Days of Summer   comedy                    Fox   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
0                 70       1.747

In [8]:
# print the first 10 records
movies.loc[0:10,:]

Film      Genre            Lead Studio  \
0            Zack and Miri Make a Porno    Romance  The Weinstein Company   
1                       Youth in Revolt     Comedy  The Weinstein Company   
2    You Will Meet a Tall Dark Stranger     Comedy            Independent   
3                          When in Rome     Comedy                 Disney   
4                 What Happens in Vegas     Comedy                    Fox   
5                   Water For Elephants      Drama       20th Century Fox   
6                                WALL-E  Animation                 Disney   
7                              Waitress    Romance            Independent   
8                   Waiting For Forever    Romance            Independent   
9                       Valentine's Day     Comedy           Warner Bros.   
10  Tyler Perry's Why Did I get Married    Romance            Independent   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
0                 70       1.747542                 64         $41.94   2008  
1                 52       1.090000                 68         $19.62   2010  
2                 35       1.211818                 43         $26.66   2010  
3                 44       0.000000                 15         $43.04   2010  
4                 72       6.267647                 28        $219.37   2008  
5                 72       3.081421                 60        $117.09   2011  
6                 89       2.896019                 96        $521.28   2008  
7                 67      11.089741                 89         $22.18   2007  
8                 53       0.005000                  6          $0.03   2011  
9                 54       4.184038                 17        $217.57   2010  
10                47       3.724192                 46         $55.86   2007

In [9]:
#What are the data types of the columns

print(movies.dtypes)


Film                  object
Genre                 object
Lead Studio           object
Audience score %       int64
Profitability        float64
Rotten Tomatoes %      int64
Worldwide Gross       object
Year                   int64
dtype: object


In [15]:
#Count of Animation movies

movies['Genre'].value_counts()

Comedy       41
Romance      13
Drama        13
Animation     4
Action        1
Fantasy       1
comedy        1
Romence       1
romance       1
Comdy         1
Name: Genre, dtype: int64

In [16]:
movies.Genre.value_counts()['Animation']

4

In [23]:
#Show the Comedy movies in the year 2007
movies[(movies['Year'] == 2007) & (movies['Genre'] == 'Comedy')] 

Film   Genre   Lead Studio  Audience score %  Profitability  \
18  The Heartbreak Kid  Comedy     Paramount                41       2.129444   
36     No Reservations  Comedy  Warner Bros.                64       3.307180   
51      License to Wed  Comedy  Warner Bros.                55       1.980206   
54          Knocked Up  Comedy     Universal                83       6.636402   
62     Good Luck Chuck  Comedy     Lionsgate                61       2.367685   
69           Enchanted  Comedy        Disney                80       4.005737   

    Rotten Tomatoes % Worldwide Gross  Year  
18                 30        $127.77   2007  
36                 39         $92.60   2007  
51                  8         $69.31   2007  
54                 91           $219   2007  
62                  3         $59.19   2007  
69                 93        $340.49   2007

In [32]:
#Count of Animation movies with more than 70% Audience Score

movies[(movies['Audience score %'] > 70) & (movies['Genre'] == 'Animation') ]

Film      Genre Lead Studio  Audience score %  Profitability  \
6    WALL-E  Animation      Disney                89       2.896019   
22  Tangled  Animation      Disney                88       1.365692   

    Rotten Tomatoes % Worldwide Gross  Year  
6                  96        $521.28   2008  
22                 89        $355.01   2010

In [5]:
#Show the list of top 5 movies based on profitability
# Question, how to show only 5?
import pandas as pd

movies = pd.read_csv ('https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv')
movies.sort_values(by = 'Profitability', ascending = False ).head(5)

Film    Genre  Lead Studio  \
68                           Fireproof    Drama  Independent   
60  High School Musical 3: Senior Year   Comedy       Disney   
14         The Twilight Saga: New Moon    Drama       Summit   
7                             Waitress  Romance  Independent   
12                            Twilight  Romance       Summit   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
68                51      66.934000                 40         $33.47   2008  
60                76      22.913136                 65        $252.04   2008  
14                78      14.196400                 27        $709.82   2009  
7                 67      11.089741                 89         $22.18   2007  
12                82      10.180027                 49        $376.66   2008

In [6]:
#Show the top 5 Comedy movies approved by the audience
# again, I didn't comand the first 5 but only got those, why? 
movies.sort_values(by = 'Audience score %', ascending = False ).head(5)

Film      Genre            Lead Studio  Audience score %  \
74    A Dangerous Method      Drama            Independent                89   
6                 WALL-E  Animation                 Disney                89   
22               Tangled  Animation                 Disney                88   
39  My Week with Marilyn      Drama  The Weinstein Company                84   
72   Across the Universe    romance            Independent                84   

    Profitability  Rotten Tomatoes % Worldwide Gross  Year  
74       0.448645                 79          $8.97   2011  
6        2.896019                 96        $521.28   2008  
22       1.365692                 89        $355.01   2010  
39       0.825800                 83          $8.26   2011  
72       0.652603                 54         $29.37   2007

In [14]:
import pandas as pd

movies = pd.read_csv ('https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv')

movies[movies['Audience score %'] > 70 ] 


Film      Genre            Lead Studio  \
4                 What Happens in Vegas     Comedy                    Fox   
5                   Water For Elephants      Drama       20th Century Fox   
6                                WALL-E  Animation                 Disney   
12                             Twilight    Romance                 Summit   
14          The Twilight Saga: New Moon      Drama                 Summit   
16                         The Proposal     Comedy                 Disney   
20  The Curious Case of Benjamin Button    Fantasy           Warner Bros.   
22                              Tangled  Animation                 Disney   
27                     Sex and the City     Comedy           Warner Bros.   
30                             Penelope     Comedy                 Summit   
31                      P.S. I Love You    Romance            Independent   
39                 My Week with Marilyn      Drama  The Weinstein Company   
43                    Midnight in Paris    Romence                   Sony   
44                        Marley and Me     Comedy                    Fox   
45                           Mamma Mia!     Comedy              Universal   
46                           Mamma Mia!     Comedy              Universal   
54                           Knocked Up     Comedy              Universal   
57                            Jane Eyre    Romance              Universal   
60   High School Musical 3: Senior Year     Comedy                 Disney   
69                            Enchanted     Comedy                 Disney   
71                            Beginners     Comedy            Independent   
72                  Across the Universe    romance            Independent   
74                   A Dangerous Method      Drama            Independent   
75                           27 Dresses     Comedy                    Fox   
76                 (500) Days of Summer     comedy                    Fox   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
4                 72       6.267647                 28        $219.37   2008  
5                 72       3.081421                 60        $117.09   2011  
6                 89       2.896019                 96        $521.28   2008  
12                82      10.180027                 49        $376.66   2008  
14                78      14.196400                 27        $709.82   2009  
16                74       7.867500                 43        $314.70   2009  
20                81       1.783944                 73        $285.43   2008  
22                88       1.365692                 89        $355.01   2010  
27                81       7.221796                 49        $415.25   2008  
30                74       1.382800                 52         $20.74   2008  
31                82       5.103117                 21        $153.09   2007  
39                84       0.825800                 83          $8.26   2011  
43                84       8.744706                 93        $148.66   2011  
44                77       3.746782                 63        $206.07   2008  
45                76       9.234454                 53        $609.47   2008  
46                76       9.234454                 53        $609.47   2008  
54                83       6.636402                 91           $219   2007  
57                77       0.000000                 85         $30.15   2011  
60                76      22.913136                 65        $252.04   2008  
69                80       4.005737                 93        $340.49   2007  
71                80       4.471875                 84         $14.31   2011  
72                84       0.652603                 54         $29.37   2007  
74                89       0.448645                 79          $8.97   2011  
75                71       5.343622                 40        $160.31   2008  
76                81       8.096000                 87   

In [17]:
movies[(movies['Audience score %'] > 70) & (movies['Lead Studio'] == 'Disney') ]

Film      Genre Lead Studio  \
6                               WALL-E  Animation      Disney   
16                        The Proposal     Comedy      Disney   
22                             Tangled  Animation      Disney   
60  High School Musical 3: Senior Year     Comedy      Disney   
69                           Enchanted     Comedy      Disney   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
6                 89       2.896019                 96        $521.28   2008  
16                74       7.867500                 43        $314.70   2009  
22                88       1.365692                 89        $355.01   2010  
60                76      22.913136                 65        $252.04   2008  
69                80       4.005737                 93        $340.49   2007

In [20]:
movies.sort_values(['Audience score %', 'Worldwide Gross'], ascending = [False, False])

Film      Genre            Lead Studio  \
74                  A Dangerous Method      Drama            Independent   
6                               WALL-E  Animation                 Disney   
22                             Tangled  Animation                 Disney   
39                My Week with Marilyn      Drama  The Weinstein Company   
72                 Across the Universe    romance            Independent   
..                                 ...        ...                    ...   
55                             Killers     Action              Lionsgate   
3                         When in Rome     Comedy                 Disney   
18                  The Heartbreak Kid     Comedy              Paramount   
48                        Love Happens      Drama              Universal   
2   You Will Meet a Tall Dark Stranger     Comedy            Independent   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
74                89       0.448645                 79          $8.97   2011  
6                 89       2.896019                 96        $521.28   2008  
22                88       1.365692                 89        $355.01   2010  
39                84       0.825800                 83          $8.26   2011  
72                84       0.652603                 54         $29.37   2007  
..               ...            ...                ...             ...   ...  
55                45       1.245333                 11         $93.40   2010  
3                 44       0.000000                 15         $43.04   2010  
18                41       2.129444                 30        $127.77   2007  
48                40       2.004444                 18         $36.08   2009  
2                 35       1.211818                 43         $26.66   2010  

[77 rows x 8 columns]

In [21]:
# Which Genre is favored the most by the Audience ? 
new = movies.groupby(['Genre']).agg({'Audience score %': ['mean']}).reset_index()


In [22]:
print(new)

       Genre Audience score %
                         mean
0     Action        45.000000
1  Animation        70.250000
2      Comdy        61.000000
3     Comedy        60.975610
4      Drama        67.230769
5    Fantasy        81.000000
6    Romance        62.769231
7    Romence        84.000000
8     comedy        81.000000
9    romance        84.000000


In [23]:
#cleaning database
movies['Genre'] = movies['Genre'].replace(['Comdy','comedy','Romence','romance'],['Comedy','Comedy','Romance','Romance'])


In [24]:
new = movies.groupby(['Genre']).agg({'Audience score %': ['mean']}).reset_index()

In [26]:
print(new)

       Genre Audience score %
                         mean
0     Action        45.000000
1  Animation        70.250000
2     Comedy        61.441860
3      Drama        67.230769
4    Fantasy        81.000000
5    Romance        65.600000


In [33]:
# Top 5 movie names by Rotten Tomato Score
movies.sort_values(by = 'Rotten Tomatoes %', ascending = False ).head(5) 

Film      Genre Lead Studio  Audience score %  Profitability  \
6              WALL-E  Animation      Disney                89       2.896019   
43  Midnight in Paris    Romance        Sony                84       8.744706   
69          Enchanted     Comedy      Disney                80       4.005737   
54         Knocked Up     Comedy   Universal                83       6.636402   
22            Tangled  Animation      Disney                88       1.365692   

    Rotten Tomatoes % Worldwide Gross  Year  
6                  96        $521.28   2008  
43                 93        $148.66   2011  
69                 93        $340.49   2007  
54                 91           $219   2007  
22                 89        $355.01   2010

In [34]:
movies.sort_values(by = 'Rotten Tomatoes %', ascending = False ).head(5) ['Film']

6                WALL-E
43    Midnight in Paris
69            Enchanted
54           Knocked Up
22              Tangled
Name: Film, dtype: object

In [35]:
#Most & Least Frequent lead studio in the dataset in terms of occurances.
movies.groupby(['Lead Studio']).sum()

Audience score %  Profitability  Rotten Tomatoes %  \
Lead Studio                                                                 
20th Century Fox                    122       5.064621                 98   
CBS                                  47       2.202571                 20   
Disney                              555      49.824029                513   
Fox                                 414      27.069134                311   
Independent                        1191     118.476823                864   
Lionsgate                           106       3.613018                 14   
New Line                             47       2.071000                 15   
Paramount                           234      10.376000                185   
Sony                                278      19.345304                208   
Summit                              366      31.889810                196   
The Weinstein Company               206       3.663342                215   
Universal                           528      35.850227                466   
Warner Bros.                        813      44.714343                491   

                        Year  
Lead Studio                   
20th Century Fox        4022  
CBS                     2010  
Disney                 16074  
Fox                    12053  
Independent            38176  
Lionsgate               4017  
New Line                2008  
Paramount               8034  
Sony                    8037  
Summit                 10045  
The Weinstein Company   6029  
Universal              16071  
Warner Bros.           28123

In [40]:
freq = movies.groupby(['Lead Studio']).count() 
print(freq)

                       Film  Genre  Audience score %  Profitability  \
Lead Studio                                                           
20th Century Fox          2      2                 2              2   
CBS                       1      1                 1              1   
Disney                    8      8                 8              8   
Fox                       6      6                 6              6   
Independent              19     19                19             19   
Lionsgate                 2      2                 2              2   
New Line                  1      1                 1              1   
Paramount                 4      4                 4              4   
Sony                      4      4                 4              4   
Summit                    5      5                 5              5   
The Weinstein Company     3      3                 3              3   
Universal                 8      8                 8              8   
Warner