In [1]:
a = np.array([1, 2, 3]) 
print(type(a))  

NameError: name 'np' is not defined

In [2]:
pip --version

pip 20.2.4 from /home/anita/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
Note: you may need to restart the kernel to use updated packages.


In [3]:
python -m pip install --upgrade pip setuptools wheel


SyntaxError: invalid syntax (<ipython-input-3-e5740273f038>, line 1)

In [4]:
--upgrade pip setuptools wheel


SyntaxError: invalid syntax (<ipython-input-4-2088398e08f5>, line 1)

In [2]:
import numpy as np  

In [8]:
import numpy as np
array_A = np.array(1, 2)

print(array_A)

TypeError: Cannot interpret '2' as a data type

In [9]:
a = np.zeros(3)

In [10]:
python -m pip install --upgrade pip

SyntaxError: invalid syntax (<ipython-input-10-0a8cf7b99133>, line 1)

In [11]:
import numpy as np

In [15]:
a = np.array([1, 2, 3])
print(type(a)) 
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [17]:
array_A = np.array([1, 2, 3, 4])

print(array_A)

[1 2 3 4]


In [22]:
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [25]:
b = np.ones((1,2,3,4))
print(b)

[[[[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]

  [[1. 1. 1. 1.]
   [1. 1. 1. 1.]
   [1. 1. 1. 1.]]]]


In [28]:
c = np.full((2,2,2,2), 7)
print(c)

[[[[7 7]
   [7 7]]

  [[7 7]
   [7 7]]]


 [[[7 7]
   [7 7]]

  [[7 7]
   [7 7]]]]


In [3]:
import numpy as np
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


In [3]:
import pandas as pd

movies = pd.read_csv ('https://gist.githubusercontent.com/tiangechen/b68782efa49a16edaf07dc2cdaa855ea/raw/0c794a9717f18b094eabab2cd6a6b9a226903577/movies.csv')

print(movies)

                                  Film    Genre            Lead Studio  \
0           Zack and Miri Make a Porno  Romance  The Weinstein Company   
1                      Youth in Revolt   Comedy  The Weinstein Company   
2   You Will Meet a Tall Dark Stranger   Comedy            Independent   
3                         When in Rome   Comedy                 Disney   
4                What Happens in Vegas   Comedy                    Fox   
..                                 ...      ...                    ...   
72                 Across the Universe  romance            Independent   
73                       A Serious Man    Drama              Universal   
74                  A Dangerous Method    Drama            Independent   
75                          27 Dresses   Comedy                    Fox   
76                (500) Days of Summer   comedy                    Fox   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
0                 70       1.747

In [8]:
# print the first 10 records
movies.loc[0:10,:]

Film      Genre            Lead Studio  \
0            Zack and Miri Make a Porno    Romance  The Weinstein Company   
1                       Youth in Revolt     Comedy  The Weinstein Company   
2    You Will Meet a Tall Dark Stranger     Comedy            Independent   
3                          When in Rome     Comedy                 Disney   
4                 What Happens in Vegas     Comedy                    Fox   
5                   Water For Elephants      Drama       20th Century Fox   
6                                WALL-E  Animation                 Disney   
7                              Waitress    Romance            Independent   
8                   Waiting For Forever    Romance            Independent   
9                       Valentine's Day     Comedy           Warner Bros.   
10  Tyler Perry's Why Did I get Married    Romance            Independent   

    Audience score %  Profitability  Rotten Tomatoes % Worldwide Gross  Year  
0                 70       1.747542                 64         $41.94   2008  
1                 52       1.090000                 68         $19.62   2010  
2                 35       1.211818                 43         $26.66   2010  
3                 44       0.000000                 15         $43.04   2010  
4                 72       6.267647                 28        $219.37   2008  
5                 72       3.081421                 60        $117.09   2011  
6                 89       2.896019                 96        $521.28   2008  
7                 67      11.089741                 89         $22.18   2007  
8                 53       0.005000                  6          $0.03   2011  
9                 54       4.184038                 17        $217.57   2010  
10                47       3.724192                 46         $55.86   2007

In [9]:
#What are the data types of the columns

print(movies.dtypes)


Film                  object
Genre                 object
Lead Studio           object
Audience score %       int64
Profitability        float64
Rotten Tomatoes %      int64
Worldwide Gross       object
Year                   int64
dtype: object


In [15]:
#Count of Animation movies

movies['Genre'].value_counts()

Comedy       41
Romance      13
Drama        13
Animation     4
Action        1
Fantasy       1
comedy        1
Romence       1
romance       1
Comdy         1
Name: Genre, dtype: int64

In [16]:
movies.Genre.value_counts()['Animation']

4